# Generated by Django 4.2.7 on 2023-11-18 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='profile_image/')),
                ('status', models.CharField(choices=[('Busy', 'Busy'), ('Available', 'Available')], max_length=10)),
                ('account_type', models.CharField(choices=[('Passenger', 'Passenger'), ('Driver', 'Driver')], max_length=10)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_image/')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to='MoverApp.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TripRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_request_status', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='MoverApp.personmodel')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='MoverApp.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.CharField(max_length=100)),
                ('end_to', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('comments', models.CharField(max_length=200)),
                ('initiated', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='MoverApp.personmodel')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='MoverApp.personmodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoverApp.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_owner', to='MoverApp.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_owner', to='MoverApp.personmodel')),
            ],
        ),
    ]
