# Generated by Django 4.2.7 on 2023-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoverApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='avg_speed',
            field=models.FloatField(),
        ),
    ]
