# Generated by Django 4.2.7 on 2023-11-18 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoverApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequestmodel',
            old_name='trip_request_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
