# Generated by Django 4.2.7 on 2023-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoverApp', '0002_alter_vehiclemodel_avg_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmodel',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
