# Generated by Django 4.2.7 on 2023-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoverApp', '0003_alter_tripmodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
