# Generated by Django 4.2.7 on 2023-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoverApp', '0005_delete_triprequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmodel',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
